// Initial seed data mirroring Spring Boot schema.sql & data.sql
// Fully focused on Chennai Localities & Neighborhoods (Porur, Adyar, Anna Nagar, etc.)

export const INITIAL_DONORS = [
  {
    id: 1,
    fullName: "Mohammed Salman",
    bloodGroup: "A+",
    gender: "Male",
    age: 26,
    phone: "9876543210",
    email: "salman@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Anna Nagar",
    address: "Anna Nagar West, 2nd Avenue",
    lastDonatedDate: "2026-05-15",
    isAvailable: true,
    totalDonations: 4,
    verified: true,
  },
  {
    id: 2,
    fullName: "Arun Kumar",
    bloodGroup: "O+",
    gender: "Male",
    age: 29,
    phone: "9944332211",
    email: "arun.k@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "T. Nagar",
    address: "T. Nagar, 4th Cross Road",
    lastDonatedDate: "2026-04-10",
    isAvailable: true,
    totalDonations: 6,
    verified: true,
  },
  {
    id: 3,
    fullName: "Priya Sundaram",
    bloodGroup: "B-",
    gender: "Female",
    age: 24,
    phone: "9000099999",
    email: "priya.s@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Porur",
    address: "Porur, Near Sri Ramachandra Hospital",
    lastDonatedDate: "2026-02-18",
    isAvailable: true,
    totalDonations: 2,
    verified: true,
  },
  {
    id: 4,
    fullName: "Vijay Raghavan",
    bloodGroup: "O-",
    gender: "Male",
    age: 33,
    phone: "9840112233",
    email: "vijay.r@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Adyar",
    address: "Adyar Main Road, Near Cancer Institute",
    lastDonatedDate: "2026-06-20",
    isAvailable: true,
    totalDonations: 8,
    verified: true,
  },
  {
    id: 5,
    fullName: "Dr. Sneha Pillai",
    bloodGroup: "AB+",
    gender: "Female",
    age: 31,
    phone: "9744112244",
    email: "sneha.p@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Velachery",
    address: "Velachery Bypass Road, Vijaya Nagar",
    lastDonatedDate: "2026-03-02",
    isAvailable: true,
    totalDonations: 3,
    verified: true,
  },
  {
    id: 6,
    fullName: "Kavitha Mani",
    bloodGroup: "A-",
    gender: "Female",
    age: 27,
    phone: "9988776655",
    email: "kavitha@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Guindy",
    address: "Guindy Industrial Estate / Kathipara",
    lastDonatedDate: "2026-07-01",
    isAvailable: true,
    totalDonations: 1,
    verified: true,
  },
  {
    id: 7,
    fullName: "Karthik Raja",
    bloodGroup: "B+",
    gender: "Male",
    age: 30,
    phone: "9841234567",
    email: "karthik.r@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Tambaram",
    address: "West Tambaram, GST Road",
    lastDonatedDate: "2026-05-30",
    isAvailable: true,
    totalDonations: 5,
    verified: true,
  },
  {
    id: 8,
    fullName: "Anand Babu",
    bloodGroup: "AB-",
    gender: "Male",
    age: 35,
    phone: "9443219876",
    email: "anand.b@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Mylapore",
    address: "Luz Church Road, Mylapore",
    lastDonatedDate: "2026-01-12",
    isAvailable: true,
    totalDonations: 7,
    verified: true,
  },
  {
    id: 9,
    fullName: "Divya Krishnan",
    bloodGroup: "O+",
    gender: "Female",
    age: 28,
    phone: "9840223344",
    email: "divya.k@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Porur",
    address: "Mount-Poonamallee High Road, Porur",
    lastDonatedDate: "2026-05-01",
    isAvailable: true,
    totalDonations: 4,
    verified: true,
  },
  {
    id: 10,
    fullName: "Rajesh Varma",
    bloodGroup: "A+",
    gender: "Male",
    age: 36,
    phone: "9790887766",
    email: "rajesh.v@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Adyar",
    address: "Kasturba Nagar, 3rd Cross Street, Adyar",
    lastDonatedDate: "2026-04-18",
    isAvailable: true,
    totalDonations: 5,
    verified: true,
  },
  {
    id: 11,
    fullName: "Meera Chandran",
    bloodGroup: "B+",
    gender: "Female",
    age: 27,
    phone: "9444433333",
    email: "meera.c@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Besant Nagar",
    address: "Besant Nagar, 4th Main Road Beach View",
    lastDonatedDate: "2025-12-01",
    isAvailable: true,
    totalDonations: 5,
    verified: true,
  },
  {
    id: 12,
    fullName: "Senthil Kumar",
    bloodGroup: "O-",
    gender: "Male",
    age: 32,
    phone: "9841889900",
    email: "senthil.k@example.com",
    city: "Chennai",
    district: "Chennai",
    area: "Vadapalani",
    address: "100 Feet Road, Near SIMS Hospital, Vadapalani",
    lastDonatedDate: "2026-06-11",
    isAvailable: true,
    totalDonations: 6,
    verified: true,
  }
];

export const INITIAL_INVENTORY = [
  { id: 1, bloodGroup: "A+", unitsAvailable: 24, reservedUnits: 2, criticalThreshold: 5 },
  { id: 2, bloodGroup: "A-", unitsAvailable: 6, reservedUnits: 1, criticalThreshold: 4 },
  { id: 3, bloodGroup: "B+", unitsAvailable: 18, reservedUnits: 3, criticalThreshold: 5 },
  { id: 4, bloodGroup: "B-", unitsAvailable: 4, reservedUnits: 1, criticalThreshold: 4 },
  { id: 5, bloodGroup: "O+", unitsAvailable: 32, reservedUnits: 4, criticalThreshold: 8 },
  { id: 6, bloodGroup: "O-", unitsAvailable: 5, reservedUnits: 2, criticalThreshold: 5 },
  { id: 7, bloodGroup: "AB+", unitsAvailable: 12, reservedUnits: 1, criticalThreshold: 3 },
  { id: 8, bloodGroup: "AB-", unitsAvailable: 3, reservedUnits: 0, criticalThreshold: 3 },
];

export const INITIAL_REQUESTS = [
  {
    id: 1,
    trackingCode: "REQ-2026-1001",
    patientName: "Rahman Sheriff",
    bloodGroup: "O+",
    unitsRequired: 2,
    hospitalName: "Apollo Speciality Hospitals",
    city: "Chennai",
    district: "Chennai",
    area: "Thousand Lights",
    contactPerson: "Fathima Rahman",
    contactPhone: "9876501234",
    urgency: "URGENT",
    status: "PENDING",
    requiredDate: "2026-09-24",
    medicalReason: "Cardiac bypass scheduled surgery",
    adminRemarks: "",
    createdAt: "2026-09-22T08:00:00Z",
  },
  {
    id: 2,
    trackingCode: "REQ-2026-1002",
    patientName: "Kavitha R.",
    bloodGroup: "O-",
    unitsRequired: 2,
    hospitalName: "Sri Ramachandra Medical Center",
    city: "Chennai",
    district: "Chennai",
    area: "Porur",
    contactPerson: "R. Rangarajan",
    contactPhone: "9876540001",
    urgency: "CRITICAL",
    status: "APPROVED",
    requiredDate: "2026-09-24",
    medicalReason: "Emergency trauma cardiovascular surgery with hemorrhage",
    adminRemarks: "Allocated 2 O- units in Porur emergency wing.",
    createdAt: "2026-09-22T07:30:00Z",
  },
  {
    id: 3,
    trackingCode: "REQ-2026-1003",
    patientName: "Asha Nair",
    bloodGroup: "AB+",
    unitsRequired: 1,
    hospitalName: "Fortis Malar Hospital",
    city: "Chennai",
    district: "Chennai",
    area: "Adyar",
    contactPerson: "Suresh Nair",
    contactPhone: "9845112233",
    urgency: "NORMAL",
    status: "APPROVED",
    requiredDate: "2026-09-25",
    medicalReason: "Post-natal severe anemia transfusion support",
    adminRemarks: "Verified with Adyar blood reserve. Cross-match scheduled.",
    createdAt: "2026-09-21T14:30:00Z",
  },
  {
    id: 4,
    trackingCode: "REQ-2026-1004",
    patientName: "Master Aarav (Age 8)",
    bloodGroup: "B+",
    unitsRequired: 1,
    hospitalName: "MIOT International Hospital",
    city: "Chennai",
    district: "Chennai",
    area: "Porur",
    contactPerson: "Deepa S.",
    contactPhone: "9876540003",
    urgency: "NORMAL",
    status: "COMPLETED",
    requiredDate: "2026-09-20",
    medicalReason: "Scheduled pediatric thalassemia transfusion protocol",
    adminRemarks: "Dispensed on September 20, 2026 at Porur blood bank.",
    createdAt: "2026-09-19T10:00:00Z",
  },
  {
    id: 5,
    trackingCode: "REQ-2026-1005",
    patientName: "Vigneshwaran M",
    bloodGroup: "A-",
    unitsRequired: 2,
    hospitalName: "Madras Medical Mission",
    city: "Chennai",
    district: "Chennai",
    area: "Anna Nagar",
    contactPerson: "Revathi M",
    contactPhone: "9944112200",
    urgency: "URGENT",
    status: "PENDING",
    requiredDate: "2026-09-23",
    medicalReason: "Emergency orthopaedic reconstructive surgery",
    adminRemarks: "",
    createdAt: "2026-09-22T06:15:00Z",
  },
];
